# Generated by Django 3.2.13 on 2022-04-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='writer_name',
        ),
    ]
