# Generated by Django 3.2.13 on 2022-04-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='now_amount',
            field=models.IntegerField(default=0),
        ),
    ]
