# Generated by Django 3.2.13 on 2022-04-18 14:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_now_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 18, 14, 56, 18, 582142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
